import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from "next/font/google";
import Nav from "@/components/Nav";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-poppins",
});
const gilroy = localFont({
	src: [
		{
			path: "./fonts/gilroy/Gilroy-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/gilroy/Gilroy-Bold.ttf",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-gilroy",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={` bg-[#0F0F0F] bg-bg-image bg-no-repeat bg-cover  ${gilroy.variable} ${poppins.variable} antialiased`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
